# Generated by Django 5.1.5 on 2025-02-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
