# Generated by Django 5.1.1 on 2025-03-18 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Student', max_length=255)),
                ('phone_number', models.CharField(default='123 456-7890', max_length=15)),
                ('bio', models.TextField(blank=True, default='N/A')),
                ('street_address', models.CharField(default='123 main street', max_length=255)),
                ('city', models.CharField(default='City', max_length=100)),
                ('province', models.CharField(default='Ontario', max_length=100)),
                ('postal_code', models.CharField(default='A1A 1A1', max_length=7)),
                ('birth_date', models.DateField(default='2020-01-01')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_images/', upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
