# Generated by Django 5.1.5 on 2025-02-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default='A1A 1A1', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(default='Ontario', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address',
            field=models.CharField(default='123 main street', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='123 456-7890', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Student', max_length=255),
        ),
    ]
