# Generated by Django 5.1.5 on 2025-02-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
